export const PATIENTS_DATA = [
  {
    id: 1,
    patientName: "Akpodion Endurance",
    hospitalId: "HOSP29384756",
    gender: "Male",
    age: "21yrs",
    clinic: "Neurology",
    statusTags: ["New", "+1"],
    walletBalance: 120000,
    time: "11:30 AM",
    date: "22 Sep 2025",
    status: "Processing",
    statusColor: "yellow",
    selected: false
  },
  {
    id: 2,
    patientName: "Boluwatife Olusola",
    hospitalId: "HOSP87654321",
    gender: "Female",
    age: "30yrs",
    clinic: "Ear, Nose & Throat",
    statusTags: ["New"],
    walletBalance: 230500,
    time: "05:30 PM",
    date: "22 Sep 2025",
    status: "Not arrived",
    statusColor: "red",
    selected: false
  },
  {
    id: 3,
    patientName: "Arlie Mertz",
    hospitalId: "HOSP76354892",
    gender: "Female",
    age: "23days",
    clinic: "Neurology",
    statusTags: ["New"],
    walletBalance: 90000,
    time: "03:45 PM",
    date: "22 Sep 2025",
    status: "Awaiting vitals",
    statusColor: "purple",
    selected: true
  },
  {
    id: 4,
    patientName: "Akuchi Amadi",
    hospitalId: "HOSP98765432",
    gender: "Female",
    age: "11mths",
    clinic: "Accident & Emergency",
    statusTags: [],
    walletBalance: 100000,
    time: "02:00 PM",
    date: "22 Sep 2025",
    status: "Not arrived",
    statusColor: "red",
    selected: true
  },
  {
    id: 5,
    patientName: "Omolola Bakare",
    hospitalId: "HOSP23456789",
    gender: "Female",
    age: "26yrs",
    clinic: "Accident & Emergency",
    statusTags: [],
    walletBalance: 180000,
    time: "01:15 PM",
    date: "22 Sep 2025",
    status: "Awaiting doctor",
    statusColor: "purple",
    selected: false
  },
  {
    id: 6,
    patientName: "Ayobami Musa",
    hospitalId: "HOSP34567890",
    gender: "Female",
    age: "11mths",
    clinic: "Accident & Emergency",
    statusTags: [],
    walletBalance: 190000,
    time: "12:45 PM",
    date: "22 Sep 2025",
    status: "Admitted to ward",
    statusColor: "orange",
    selected: false
  },
  {
    id: 7,
    patientName: "Ngozi Okeke",
    hospitalId: "HOSP45678901",
    gender: "Female",
    age: "11mths",
    clinic: "Accident & Emergency",
    statusTags: [],
    walletBalance: 200000,
    time: "10:00 AM",
    date: "22 Sep 2025",
    status: "Transferred to A&E",
    statusColor: "purple",
    selected: true
  },
  {
    id: 8,
    patientName: "Chinwe Azikiwe",
    hospitalId: "HOSP56789012",
    gender: "Female",
    age: "11mths",
    clinic: "Accident & Emergency",
    statusTags: [],
    walletBalance: 210000,
    time: "08:00 AM",
    date: "22 Sep 2025",
    status: "Seen doctor",
    statusColor: "green",
    selected: false
  },

  // ---- Auto-generated below ----
  {
    id: 9,
    patientName: "Tunde Adewale",
    hospitalId: "HOSP70000009",
    gender: "Male",
    age: "44yrs",
    clinic: "Paediatrics",
    statusTags: [],
    walletBalance: 148000,
    time: "07:15 AM",
    date: "22 Sep 2025",
    status: "Processing",
    statusColor: "yellow",
    selected: true
  },
  {
    id: 10,
    patientName: "Nneka Ibekwe",
    hospitalId: "HOSP70000010",
    gender: "Female",
    age: "36yrs",
    clinic: "Cardiology",
    statusTags: ["New"],
    walletBalance: 222000,
    time: "08:42 AM",
    date: "22 Sep 2025",
    status: "Not arrived",
    statusColor: "red",
    selected: false
  },
  {
    id: 11,
    patientName: "Fatima Bello",
    hospitalId: "HOSP70000011",
    gender: "Female",
    age: "52yrs",
    clinic: "Orthopaedics",
    statusTags: [],
    walletBalance: 196000,
    time: "09:05 AM",
    date: "22 Sep 2025",
    status: "Awaiting vitals",
    statusColor: "purple",
    selected: true
  },
  {
    id: 12,
    patientName: "Michael Eze",
    hospitalId: "HOSP70000012",
    gender: "Male",
    age: "29yrs",
    clinic: "Oncology",
    statusTags: [],
    walletBalance: 173000,
    time: "09:55 AM",
    date: "22 Sep 2025",
    status: "Awaiting doctor",
    statusColor: "purple",
    selected: false
  },
  {
    id: 13,
    patientName: "Jennifer Okafor",
    hospitalId: "HOSP70000013",
    gender: "Female",
    age: "61yrs",
    clinic: "Psychiatry",
    statusTags: [],
    walletBalance: 244000,
    time: "10:33 AM",
    date: "22 Sep 2025",
    status: "Admitted to ward",
    statusColor: "orange",
    selected: false
  },
  {
    id: 14,
    patientName: "David Chu",
    hospitalId: "HOSP70000014",
    gender: "Male",
    age: "14yrs",
    clinic: "Dermatology",
    statusTags: ["+1"],
    walletBalance: 129000,
    time: "11:12 AM",
    date: "22 Sep 2025",
    status: "Transferred to A&E",
    statusColor: "purple",
    selected: true
  },
  {
    id: 15,
    patientName: "Helen Smith",
    hospitalId: "HOSP70000015",
    gender: "Female",
    age: "47yrs",
    clinic: "General Surgery",
    statusTags: [],
    walletBalance: 205000,
    time: "12:26 PM",
    date: "22 Sep 2025",
    status: "Seen doctor",
    statusColor: "green",
    selected: false
  },
  {
    id: 16,
    patientName: "Samira Khan",
    hospitalId: "HOSP70000016",
    gender: "Female",
    age: "33yrs",
    clinic: "Urology",
    statusTags: [],
    walletBalance: 157000,
    time: "01:40 PM",
    date: "22 Sep 2025",
    status: "Processing",
    statusColor: "yellow",
    selected: false
  },
  {
    id: 17,
    patientName: "Alex Johnson",
    hospitalId: "HOSP70000017",
    gender: "Male",
    age: "55yrs",
    clinic: "Ear, Nose & Throat",
    statusTags: [],
    walletBalance: 98000,
    time: "02:18 PM",
    date: "22 Sep 2025",
    status: "Not arrived",
    statusColor: "red",
    selected: true
  },
  {
    id: 18,
    patientName: "Chiamaka Obiora",
    hospitalId: "HOSP70000018",
    gender: "Female",
    age: "24yrs",
    clinic: "Neurology",
    statusTags: [],
    walletBalance: 184000,
    time: "03:03 PM",
    date: "22 Sep 2025",
    status: "Awaiting vitals",
    statusColor: "purple",
    selected: false
  },
  {
    id: 19,
    patientName: "Kenzo Sato",
    hospitalId: "HOSP70000019",
    gender: "Male",
    age: "62yrs",
    clinic: "Paediatrics",
    statusTags: [],
    walletBalance: 141000,
    time: "04:27 PM",
    date: "22 Sep 2025",
    status: "Awaiting doctor",
    statusColor: "purple",
    selected: true
  },
  {
    id: 20,
    patientName: "Leah Miller",
    hospitalId: "HOSP70000020",
    gender: "Female",
    age: "19yrs",
    clinic: "Cardiology",
    statusTags: [],
    walletBalance: 213000,
    time: "05:16 PM",
    date: "22 Sep 2025",
    status: "Admitted to ward",
    statusColor: "orange",
    selected: false
  },
];
